language: ruby
before_install:
  - gem update bundler
gemfile:
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
  - gemfiles/rails_master.gemfile
script: bundle exec rake spec
rvm:
  - 2.7.2
  - 2.6.6
  - 2.5.7
